# rr-events/nixpacks.toml

[phases.setup]
nixpkgsArchive = "22.11"

[phases.install]
cmds = ["dotnet restore"]

[phases.build]
cmds = ["dotnet publish src/rr-events.csproj -c Release -o out"]

[start]
cmd = "dotnet out/rr-events.dll"
